# https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b
FROM registry.access.redhat.com/ubi9@sha256:cecb1cde7bda7c8165ae27841c2335667f8a3665a349c0d051329c61660a496c

RUN dnf -y --noplugins --setopt=install_weak_deps=0 --setopt=tsflags=nodocs upgrade
RUN INSTALL_PKGS="jq wget unzip zip git skopeo" && \
    dnf --disableplugin=subscription-manager -y --nodocs --setopt=install_weak_deps=0 install $INSTALL_PKGS && \
    dnf clean all && \
    rm -rf /var/cache/* /var/log/dnf* /var/log/yum.*

RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
RUN chmod a+x /usr/local/bin/yq

WORKDIR /workdir

ENV HOME=/workdir

RUN chown -R 65532:0 /workdir && \
    chmod -R g=u /workdir

USER 65532

COPY --chown=65532:0 \
    podman/syft-agent/install.sh \
    /workdir/

RUN sh -c ./install.sh && rm ./install.sh

# Expose Syft and Java to the default PATH
ENV PATH="$HOME/syft:$HOME/.sdkman/candidates/java/current/bin:$PATH"